-- AlterTable
ALTER TABLE `documents` ADD COLUMN `withholdingTax` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `withholdingTaxAddress` TEXT NULL,
    ADD COLUMN `withholdingTaxApprover` VARCHAR(200) NULL,
    ADD COLUMN `withholdingTaxRate` DECIMAL(5, 2) NULL,
    ADD COLUMN `withholdingTaxRecipient` VARCHAR(200) NULL;

-- CreateTable
CREATE TABLE `Asset` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `source` ENUM('LED', 'BAAC', 'NHA', 'GSB', 'GHB', 'SAM') NOT NULL DEFAULT 'LED',
    `sourceAssetId` VARCHAR(100) NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `auctionLot` VARCHAR(100) NOT NULL,
    `bidNumber` VARCHAR(50) NOT NULL,
    `caseNumber` VARCHAR(100) NULL,
    `deedNo` VARCHAR(500) NULL,
    `assetType` VARCHAR(100) NOT NULL,
    `assetTypeId` VARCHAR(10) NULL,
    `rai` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `ngan` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `sqWa` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `appraisalPrice` DECIMAL(15, 2) NULL,
    `reserveFund` DECIMAL(15, 2) NULL,
    `reserveFund1` DECIMAL(15, 2) NULL,
    `address` VARCHAR(255) NULL,
    `tambol` VARCHAR(100) NULL,
    `ampur` VARCHAR(100) NULL,
    `province` VARCHAR(100) NULL,
    `status` ENUM('ACTIVE', 'SOLD', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,
    `scrapedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `scrapeLogId` INTEGER NULL,

    INDEX `Asset_source_auctionLot_bidNumber_deedNo_assetTypeId_idx`(`source`, `auctionLot`, `bidNumber`, `deedNo`, `assetTypeId`),
    INDEX `Asset_source_sourceAssetId_idx`(`source`, `sourceAssetId`),
    INDEX `Asset_source_idx`(`source`),
    INDEX `Asset_province_idx`(`province`),
    INDEX `Asset_ampur_idx`(`ampur`),
    INDEX `Asset_assetType_idx`(`assetType`),
    INDEX `Asset_appraisalPrice_idx`(`appraisalPrice`),
    INDEX `Asset_caseNumber_idx`(`caseNumber`),
    INDEX `Asset_deedNo_idx`(`deedNo`),
    INDEX `Asset_scrapedAt_idx`(`scrapedAt`),
    INDEX `Asset_scrapeLogId_idx`(`scrapeLogId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AssetDetail` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `assetId` INTEGER NOT NULL,
    `courtName` VARCHAR(100) NULL,
    `courtId` VARCHAR(10) NULL,
    `lawSuitNo` VARCHAR(50) NULL,
    `lawSuitYear` VARCHAR(10) NULL,
    `deedNo` VARCHAR(500) NULL,
    `deedTambol` VARCHAR(100) NULL,
    `deedAmpur` VARCHAR(100) NULL,
    `deedCity` VARCHAR(100) NULL,
    `landType` VARCHAR(100) NULL,
    `landDesc` VARCHAR(255) NULL,
    `ownerName` VARCHAR(255) NULL,
    `ownerSuitName` VARCHAR(255) NULL,
    `plaintiff` VARCHAR(255) NULL,
    `defendant` VARCHAR(255) NULL,
    `occupant` VARCHAR(255) NULL,
    `saleLocation1` TEXT NULL,
    `saleLocation2` TEXT NULL,
    `saleTime1` VARCHAR(20) NULL,
    `saleTime2` VARCHAR(20) NULL,
    `saleType` VARCHAR(100) NULL,
    `price1` DECIMAL(15, 2) NULL,
    `price2` DECIMAL(15, 2) NULL,
    `price3` DECIMAL(15, 2) NULL,
    `price4` DECIMAL(15, 2) NULL,
    `price5` DECIMAL(15, 2) NULL,
    `price6` DECIMAL(15, 2) NULL,
    `price7` DECIMAL(15, 2) NULL,
    `price8` DECIMAL(15, 2) NULL,
    `tel` VARCHAR(50) NULL,
    `remark` TEXT NULL,
    `remark1` TEXT NULL,
    `eauc` VARCHAR(10) NULL,
    `landPicture` VARCHAR(500) NULL,
    `map` VARCHAR(500) NULL,
    `mapJot` VARCHAR(500) NULL,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,

    UNIQUE INDEX `AssetDetail_assetId_key`(`assetId`),
    INDEX `AssetDetail_assetId_idx`(`assetId`),
    INDEX `AssetDetail_deedNo_idx`(`deedNo`),
    INDEX `AssetDetail_ownerName_idx`(`ownerName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BidSchedule` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `assetId` INTEGER NOT NULL,
    `roundNumber` INTEGER NOT NULL,
    `bidDate` DATETIME(0) NOT NULL,
    `price` DECIMAL(15, 2) NULL,
    `isSale` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `BidSchedule_assetId_idx`(`assetId`),
    INDEX `BidSchedule_bidDate_idx`(`bidDate`),
    UNIQUE INDEX `BidSchedule_assetId_roundNumber_key`(`assetId`, `roundNumber`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LandDeedInfo` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `assetId` INTEGER NOT NULL,
    `provName` VARCHAR(100) NULL,
    `amphurName` VARCHAR(100) NULL,
    `tumbolName` VARCHAR(100) NULL,
    `landOffice` VARCHAR(255) NULL,
    `parcelType` VARCHAR(100) NULL,
    `parcelNo` VARCHAR(50) NULL,
    `landNo` VARCHAR(50) NULL,
    `surveyNo` VARCHAR(50) NULL,
    `utm` VARCHAR(100) NULL,
    `rai` INTEGER NOT NULL DEFAULT 0,
    `ngan` INTEGER NOT NULL DEFAULT 0,
    `wa` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `landPrice` VARCHAR(50) NULL,
    `latitude` DECIMAL(12, 8) NULL,
    `longitude` DECIMAL(12, 8) NULL,
    `utmZone` VARCHAR(10) NULL,
    `utmN` DECIMAL(20, 6) NULL,
    `utmE` DECIMAL(20, 6) NULL,
    `provId` VARCHAR(10) NULL,
    `amphurId` VARCHAR(10) NULL,
    `tambolId` VARCHAR(10) NULL,
    `landOfficeId` VARCHAR(20) NULL,
    `qrcodeLink` VARCHAR(500) NULL,
    `surveyPriceLink` VARCHAR(500) NULL,
    `orgTel` VARCHAR(50) NULL,
    `rawJson` JSON NULL,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,
    `fetchedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `LandDeedInfo_assetId_key`(`assetId`),
    INDEX `LandDeedInfo_assetId_idx`(`assetId`),
    INDEX `LandDeedInfo_provName_idx`(`provName`),
    INDEX `LandDeedInfo_amphurName_idx`(`amphurName`),
    INDEX `LandDeedInfo_parcelNo_idx`(`parcelNo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ScrapeLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `source` ENUM('LED', 'BAAC', 'NHA', 'GSB', 'GHB', 'SAM') NOT NULL DEFAULT 'LED',
    `searchProvince` VARCHAR(100) NULL,
    `searchParams` JSON NULL,
    `startPage` INTEGER NOT NULL DEFAULT 1,
    `endPage` INTEGER NULL,
    `totalResults` INTEGER NOT NULL DEFAULT 0,
    `totalPages` INTEGER NOT NULL DEFAULT 0,
    `itemsScraped` INTEGER NOT NULL DEFAULT 0,
    `itemsNew` INTEGER NOT NULL DEFAULT 0,
    `itemsUpdated` INTEGER NOT NULL DEFAULT 0,
    `itemsFailed` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL') NOT NULL DEFAULT 'RUNNING',
    `errorMessage` TEXT NULL,
    `startedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `completedAt` DATETIME(0) NULL,

    INDEX `ScrapeLog_source_idx`(`source`),
    INDEX `ScrapeLog_startedAt_idx`(`startedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ScrapeIssue` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `source` ENUM('LED', 'BAAC', 'NHA', 'GSB', 'GHB', 'SAM') NOT NULL,
    `scrapeLogId` INTEGER NULL,
    `pageNumber` INTEGER NULL,
    `itemIndex` INTEGER NULL,
    `auctionLot` VARCHAR(100) NULL,
    `bidNumber` VARCHAR(50) NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `assetId` INTEGER NULL,
    `issueType` ENUM('MISSING_DEED', 'MISSING_LOCATION', 'MISSING_PRICE', 'FETCH_FAILED', 'PARSE_ERROR', 'LANDDEED_FAILED', 'INCOMPLETE_DATA') NOT NULL,
    `missingFields` TEXT NULL,
    `errorMessage` TEXT NULL,
    `rawData` JSON NULL,
    `status` ENUM('PENDING', 'RETRYING', 'RESOLVED', 'IGNORED') NOT NULL DEFAULT 'PENDING',
    `retryCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,
    `resolvedAt` DATETIME(0) NULL,

    INDEX `ScrapeIssue_source_status_idx`(`source`, `status`),
    INDEX `ScrapeIssue_scrapeLogId_idx`(`scrapeLogId`),
    INDEX `ScrapeIssue_issueType_idx`(`issueType`),
    INDEX `ScrapeIssue_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
